---
- name: Copying the files to remote servers
  hosts: all
  become: yes
  tasks:
    - name: copying the blog.txt file to app server1 {{ inventory_hostname }}
      copy:
        src: /usr/src/security/blog.txt
        dest: /opt/security/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0744'
      when: inventory_hostname == 'stapp01'

    - name: copying the story.txt file to app server2 {{ inventory_hostname }}
      copy:
        src: /usr/src/security/story.txt
        dest: /opt/security/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0744'
      when: inventory_hostname == 'stapp02'

    - name: copying the media.txt file to app server3 {{ inventory_hostname }}
      copy:
        src: /usr/src/security/media.txt
        dest: /opt/security/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0744'
      when: inventory_hostname == 'stapp03'